---
sudo: required

language: python

python:
  - 2.7

addons:
  apt:
    packages:
      - python-pip

git:
  depth: 1

cache:
  apt: true
  timeout: 691200

env:
   - SITE=test.yml

install:
  - pip install ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - ansible --version
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
